### ISSUE TITLE
Unstable formatting of file with a set of comments

### ISSUE THREAD

**Issue by liutikas** [facebook/ktfmt#405]
# Repro steps

```
java  -cp /ssd/ssd5/androidx-main/prebuilts/androidx/external/com/facebook/ktfmt/0.44/ktfmt-0.44.jar:..all.jars com.facebook.ktfmt.cli.Main --kotlinlang-style src/androidTest/java/androidx/viewpager2/widget/SwipeTest.kt
```

- Try to format the following file:
```
/*
 * Copyright 2018
 */

package androidx.viewpager2.widget

// endregion

// endregion
```

# Expected
No changes are made

# Actual
ktfmt format command will insert a new space after `// endregion` every time it is run. The file just keeps getting longer and longer by one space with every call.

# Details

Using ktfmt 0.44

**Comment by davidtorosyan** [comment]
I think this fixed by #401, but will verify before closing. I think we're working on getting a release out as well.

**Comment by hick209** [comment]
I've just verified and this was indeed fixed. We do need a new release though as this is still an issue in v0.44.

I'll close once we release the next version

**Comment by hick209** [comment]
This should be fixed with the new release [v0.45](https://github.com/facebook/ktfmt/releases/tag/v0.45)
